// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredAccount } from "./StoredAccount";

export type ListAccountsResponse = { data: Array<StoredAccount>, nextCursor: string | null, };
