// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { PlanType } from "../PlanType";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type StoredAccount = { accountId: string, label: string, authMode: AuthMode, email: string | null, planType: PlanType | null, active: boolean, rateLimits: RateLimitSnapshot | null, };
